### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by aceat64** [ferno/base32768#1]
When attempting to run the example code from the README, I receive the following error:

```
$ node test.js 
/home/aceat64/node_modules/base32768/index.js:90
		var result = bits_to_bits([...buf.values()], MAGIC_NUMBER_B, MAGIC_NUMBER_A);
		                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/aceat64/test.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by ferno** [comment]
I think you'll need a version of Node.js which supports iterators. Not sure what version number that is, exactly.

**Comment by aceat64** [comment]
Yup, looks like my home desktop was on node 4.4.2, my work desktop is 5.9.0 and the library works.
